"""Filesystem storage for paired ComfyUI UI/API workflows.

The HTTP layer obtains a user-scoped root from ComfyUI's UserManager before
constructing this store. All paths below that root are generated by the bridge;
callers never supply filesystem paths.
"""

from __future__ import annotations

import copy
import hashlib
import json
import os
import re
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1
BRIDGE_VERSION = "0.1.0"
MAX_WORKFLOW_BYTES = 10 * 1024 * 1024
MAX_NAME_LENGTH = 120
MAX_NODES = 5000


class BridgeValidationError(ValueError):
    pass


class BridgeConflictError(RuntimeError):
    def __init__(self, current: dict[str, Any]):
        super().__init__("The remote workflow changed")
        self.current = current


def _canonical_json(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _content_hash(ui_workflow: dict[str, Any], api_workflow: dict[str, Any], mapping: dict[str, Any]) -> str:
    digest = hashlib.sha256()
    digest.update(_canonical_json({"uiWorkflow": ui_workflow, "apiWorkflow": api_workflow, "mapping": mapping}))
    return digest.hexdigest()


def _safe_name(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "-", name.strip()).strip("-._")
    return (value[:64] or "workflow")


def _valid_id(value: str) -> bool:
    try:
        return str(uuid.UUID(value)) == value.lower()
    except (ValueError, AttributeError):
        return False


def _validate_name(value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise BridgeValidationError("Workflow name is required")
    name = value.strip()
    if len(name) > MAX_NAME_LENGTH or any(ord(char) < 32 for char in name):
        raise BridgeValidationError("Workflow name is invalid")
    return name


def _validate_ui_workflow(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict) or not value:
        raise BridgeValidationError("uiWorkflow must be a non-empty object")
    nodes = value.get("nodes")
    if nodes is not None and (not isinstance(nodes, list) or len(nodes) > MAX_NODES):
        raise BridgeValidationError("uiWorkflow nodes are invalid")
    return copy.deepcopy(value)


def _validate_api_workflow(value: Any) -> dict[str, Any]:
    if isinstance(value, dict) and isinstance(value.get("prompt"), dict):
        value = value["prompt"]
    if not isinstance(value, dict) or not value or len(value) > MAX_NODES:
        raise BridgeValidationError("apiWorkflow must be a non-empty API-format object")
    for node_id, node in value.items():
        if not isinstance(node_id, str) or not isinstance(node, dict):
            raise BridgeValidationError("apiWorkflow contains an invalid node")
        if not isinstance(node.get("class_type"), str) or not isinstance(node.get("inputs"), dict):
            raise BridgeValidationError(f"apiWorkflow node {node_id} is not in API format")
    return copy.deepcopy(value)


def _validate_object(value: Any, field: str) -> dict[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise BridgeValidationError(f"{field} must be an object")
    return copy.deepcopy(value)


class WorkflowBridgeStore:
    def __init__(self, user_root: str | os.PathLike[str]):
        self.user_root = Path(user_root).resolve()
        self.bundle_root = self.user_root / "chatbox-bridge" / "workflows"
        self.comfy_workflow_root = self.user_root / "workflows" / "Chatbox"

    def _safe_user_path(self, relative: str | os.PathLike[str]) -> Path:
        candidate = self.user_root / relative
        resolved = candidate.resolve(strict=False)
        if os.path.commonpath((str(self.user_root), str(resolved))) != str(self.user_root):
            raise BridgeValidationError("Stored workflow path is invalid")
        return candidate

    def _bundle_path(self, workflow_id: str) -> Path:
        if not _valid_id(workflow_id):
            raise BridgeValidationError("Workflow id is invalid")
        return self._safe_user_path(Path("chatbox-bridge") / "workflows" / f"{workflow_id}.json")

    @staticmethod
    def _read_json(path: Path) -> dict[str, Any]:
        with path.open("r", encoding="utf-8") as handle:
            value = json.load(handle)
        if not isinstance(value, dict):
            raise BridgeValidationError("Stored workflow is invalid")
        return value

    @staticmethod
    def _atomic_write(path: Path, value: dict[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary = tempfile.mkstemp(prefix=".chatbox-bridge-", suffix=".tmp", dir=path.parent)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                json.dump(value, handle, ensure_ascii=False, indent=2)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(temporary, 0o600)
            os.replace(temporary, path)
        except Exception:
            try:
                os.unlink(temporary)
            except FileNotFoundError:
                pass
            raise

    @staticmethod
    def metadata(bundle: dict[str, Any]) -> dict[str, Any]:
        return {
            key: bundle[key]
            for key in (
                "schemaVersion",
                "id",
                "name",
                "revision",
                "updatedAt",
                "contentHash",
                "uiPath",
                "capabilities",
            )
            if key in bundle
        }

    def get(self, workflow_id: str) -> dict[str, Any]:
        path = self._bundle_path(workflow_id)
        if not path.is_file():
            raise FileNotFoundError(workflow_id)
        return self._read_json(path)

    def list(self) -> list[dict[str, Any]]:
        if not self.bundle_root.is_dir():
            return []
        workflows: list[dict[str, Any]] = []
        for path in self.bundle_root.glob("*.json"):
            if path.is_symlink():
                continue
            try:
                self._safe_user_path(path.relative_to(self.user_root))
                workflows.append(self.metadata(self._read_json(path)))
            except (OSError, ValueError, json.JSONDecodeError):
                continue
        workflows.sort(key=lambda item: (str(item.get("name", "")).lower(), str(item.get("id", ""))))
        return workflows

    def list_unmanaged(self) -> list[dict[str, Any]]:
        native_root = self.user_root / "workflows"
        if not native_root.is_dir():
            return []
        managed_paths = {str(item.get("uiPath", "")) for item in self.list()}
        result: list[dict[str, Any]] = []
        for path in native_root.rglob("*.json"):
            relative = path.relative_to(self.user_root).as_posix()
            if relative in managed_paths or path.is_symlink():
                continue
            self._safe_user_path(relative)
            stats = path.stat()
            result.append({"path": relative, "name": path.stem, "size": stats.st_size, "modified": int(stats.st_mtime * 1000)})
        result.sort(key=lambda item: str(item["path"]).lower())
        return result

    def save(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise BridgeValidationError("Request body must be an object")
        name = _validate_name(payload.get("name"))
        ui_workflow = _validate_ui_workflow(payload.get("uiWorkflow"))
        api_workflow = _validate_api_workflow(payload.get("apiWorkflow"))
        mapping = _validate_object(payload.get("mapping"), "mapping")
        capabilities = _validate_object(payload.get("capabilities"), "capabilities")

        extra = ui_workflow.get("extra")
        if extra is None:
            extra = {}
            ui_workflow["extra"] = extra
        if not isinstance(extra, dict):
            raise BridgeValidationError("uiWorkflow extra must be an object")
        extra.pop("chatboxBridge", None)
        content_hash = _content_hash(ui_workflow, api_workflow, mapping)

        requested_id = payload.get("id")
        workflow_id = str(uuid.uuid4()) if requested_id in (None, "") else str(requested_id).lower()
        bundle_path = self._bundle_path(workflow_id)
        existing = self._read_json(bundle_path) if bundle_path.is_file() else None
        expected_revision = payload.get("expectedRevision")
        if existing is not None:
            if not isinstance(expected_revision, int) or expected_revision != existing.get("revision"):
                raise BridgeConflictError(self.metadata(existing))
        elif expected_revision not in (None, 0):
            raise BridgeConflictError({"id": workflow_id, "revision": 0})

        revision = int(existing.get("revision", 0)) + 1 if existing else 1
        ui_path = f"workflows/Chatbox/{_safe_name(name)}--{workflow_id[:8]}.json"
        extra["chatboxBridge"] = {
            "id": workflow_id,
            "revision": revision,
            "name": name,
            "mapping": mapping,
            "capabilities": capabilities,
        }

        bundle = {
            "schemaVersion": SCHEMA_VERSION,
            "bridgeVersion": BRIDGE_VERSION,
            "id": workflow_id,
            "name": name,
            "revision": revision,
            "updatedAt": datetime.now(timezone.utc).isoformat(),
            "uiPath": ui_path,
            "uiWorkflow": ui_workflow,
            "apiWorkflow": api_workflow,
            "mapping": mapping,
            "capabilities": capabilities,
        }
        bundle["contentHash"] = content_hash

        ui_file = self._safe_user_path(ui_path)
        old_ui_file = self._safe_user_path(str(existing.get("uiPath"))) if existing and existing.get("uiPath") else None
        self._atomic_write(ui_file, ui_workflow)
        try:
            self._atomic_write(bundle_path, bundle)
        except Exception:
            if not existing:
                ui_file.unlink(missing_ok=True)
            raise
        if old_ui_file and old_ui_file != ui_file:
            old_ui_file.unlink(missing_ok=True)
        return bundle

    def delete(self, workflow_id: str, expected_revision: int | None) -> None:
        bundle_path = self._bundle_path(workflow_id)
        if not bundle_path.is_file():
            raise FileNotFoundError(workflow_id)
        existing = self._read_json(bundle_path)
        if not isinstance(expected_revision, int) or expected_revision != existing.get("revision"):
            raise BridgeConflictError(self.metadata(existing))
        ui_path = existing.get("uiPath")
        if isinstance(ui_path, str):
            self._safe_user_path(ui_path).unlink(missing_ok=True)
        bundle_path.unlink()
